import { Platform } from 'react-native';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import JSZip from 'jszip';
import { format } from 'date-fns';
import useJournalStore from './state/journal-store';
import type { JournalEntry } from './types';

function getEmotionTags(entry: JournalEntry): string {
  const tags: string[] = [];
  if (entry.primaryEmotion) tags.push(entry.primaryEmotion);
  if (entry.emotions?.length) {
    entry.emotions.forEach((e) => {
      if (!tags.includes(e)) tags.push(e);
    });
  }
  return tags.map((t) => t.charAt(0).toUpperCase() + t.slice(1)).join(', ');
}

function buildEntryHtml(entry: JournalEntry): string {
  const date = format(new Date(entry.createdAt), 'MMMM d, yyyy - h:mm a');
  const emotionTags = getEmotionTags(entry);
  const valenceLabel = entry.valence != null ? `Valence: ${entry.valence > 0 ? '+' : ''}${entry.valence}` : '';
  const arousalLabel = entry.arousal != null ? `Arousal: ${entry.arousal}` : '';
  const metaLine = [valenceLabel, arousalLabel].filter(Boolean).join(' | ');

  return `
    <div class="entry">
      <div class="entry-date">${date}</div>
      <h2 class="entry-title">${entry.title || 'Untitled Entry'}</h2>
      ${emotionTags ? `<div class="tags">${emotionTags}</div>` : ''}
      ${metaLine ? `<div class="meta">${metaLine}</div>` : ''}
      <div class="transcript">${(entry.transcript || '').replace(/\n/g, '<br/>')}</div>
      ${entry.audioUri ? '<div class="audio-note">Audio file included in archive</div>' : ''}
    </div>
  `;
}

function buildPdfHtml(entries: JournalEntry[]): string {
  const entriesHtml = entries.map(buildEntryHtml).join('<div class="page-break"></div>');
  const exportDate = format(new Date(), 'MMMM d, yyyy');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8"/>
      <style>
        @media print { .page-break { page-break-after: always; } }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a2e; padding: 40px; line-height: 1.6; }
        .header { text-align: center; margin-bottom: 48px; padding-bottom: 24px; border-bottom: 2px solid #e8e0f5; }
        .header h1 { font-size: 28px; font-weight: 700; color: #1a1a2e; margin-bottom: 8px; }
        .header p { font-size: 14px; color: #666; }
        .entry { margin-bottom: 40px; padding: 24px; border: 1px solid #e8e0f5; border-radius: 12px; background: #faf8ff; }
        .entry-date { font-size: 12px; color: #888; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 8px; }
        .entry-title { font-size: 20px; font-weight: 600; color: #1a1a2e; margin-bottom: 12px; }
        .tags { font-size: 13px; color: #7c5cbf; margin-bottom: 8px; font-weight: 500; }
        .meta { font-size: 12px; color: #999; margin-bottom: 16px; }
        .transcript { font-size: 15px; line-height: 1.7; color: #333; }
        .audio-note { margin-top: 12px; font-size: 12px; color: #7c5cbf; font-style: italic; }
        .page-break { margin: 0; padding: 0; }
        .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #aaa; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Vocolens Journal Export</h1>
        <p>Exported on ${exportDate} &middot; ${entries.length} ${entries.length === 1 ? 'entry' : 'entries'}</p>
      </div>
      ${entriesHtml}
      <div class="footer">Generated by Vocolens</div>
    </body>
    </html>
  `;
}

export interface ExportJournalOptions {
  mode: 'all' | 'custom';
  startDate: Date;
  endDate: Date;
  onProgress?: (message: string) => void;
}

export interface ExportResult {
  success: boolean;
  entryCount: number;
  error?: string;
}

export function getEntriesInRange(startDate: Date, endDate: Date): JournalEntry[] {
  const start = startDate.getTime();
  const endOfDay = new Date(endDate);
  endOfDay.setHours(23, 59, 59, 999);
  const end = endOfDay.getTime();

  return useJournalStore.getState().entries.filter((entry) => {
    const entryTime = new Date(entry.createdAt).getTime();
    return entryTime >= start && entryTime <= end;
  });
}

function downloadBlobOnWeb(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

async function generatePdfForNative(html: string): Promise<{ uri: string; isPdf: boolean }> {
  try {
    const Print = await import('expo-print');
    const { uri } = await Print.printToFileAsync({ html, base64: false });
    return { uri, isPdf: true };
  } catch {
    // expo-print native module unavailable — fall back to saving raw HTML
    const htmlPath = `${FileSystem.cacheDirectory}journal-entries.html`;
    await FileSystem.writeAsStringAsync(htmlPath, html, { encoding: FileSystem.EncodingType.UTF8 });
    return { uri: htmlPath, isPdf: false };
  }
}

export async function exportJournalArchive(options: ExportJournalOptions): Promise<ExportResult> {
  const { startDate, endDate, onProgress } = options;

  onProgress?.('Finding entries...');
  const entries = getEntriesInRange(startDate, endDate);

  if (entries.length === 0) {
    return { success: false, entryCount: 0, error: 'No entries found in this range.' };
  }

  onProgress?.(`Generating PDF for ${entries.length} entries...`);
  const html = buildPdfHtml(entries);

  const zip = new JSZip();

  if (Platform.OS === 'web') {
    zip.file('journal-entries.html', html);
  } else {
    const { uri: fileUri, isPdf } = await generatePdfForNative(html);
    const fileContent = await FileSystem.readAsStringAsync(fileUri, {
      encoding: FileSystem.EncodingType.Base64,
    });
    zip.file(isPdf ? 'journal-entries.pdf' : 'journal-entries.html', fileContent, { base64: true });
    try {
      await FileSystem.deleteAsync(fileUri, { idempotent: true });
    } catch {}
  }

  onProgress?.('Building archive...');

  if (Platform.OS !== 'web') {
    for (const entry of entries) {
      if (!entry.audioUri) continue;

      const fileInfo = await FileSystem.getInfoAsync(entry.audioUri);
      if (!fileInfo.exists) continue;

      const dateFolder = format(new Date(entry.createdAt), 'yyyy-MM-dd');
      const time = format(new Date(entry.createdAt), 'HHmmss');
      const ext = entry.audioUri.split('.').pop() || 'mp3';
      const audioFileName = `audio/${dateFolder}/${time}.${ext}`;

      try {
        const audioBase64 = await FileSystem.readAsStringAsync(entry.audioUri, {
          encoding: FileSystem.EncodingType.Base64,
        });
        zip.file(audioFileName, audioBase64, { base64: true });
      } catch {
        // Skip inaccessible audio files
      }
    }
  }

  onProgress?.('Compressing archive...');
  const dateStr = format(new Date(), 'yyyy-MM-dd');
  const zipFileName = `vocolens-journal-${dateStr}.zip`;

  if (Platform.OS === 'web') {
    const blob = await zip.generateAsync({ type: 'blob' });
    downloadBlobOnWeb(blob, zipFileName);
  } else {
    const zipBase64 = await zip.generateAsync({ type: 'base64' });
    const zipPath = `${FileSystem.cacheDirectory}${zipFileName}`;

    await FileSystem.writeAsStringAsync(zipPath, zipBase64, {
      encoding: FileSystem.EncodingType.Base64,
    });

    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(zipPath, {
        mimeType: 'application/zip',
        dialogTitle: 'Save Journal Export',
      });
    }
  }

  return { success: true, entryCount: entries.length };
}
